[package]
name = "gg_renderable_test"
version = "0.1.0"
authors = ["Alex Jones <alexander.jones@softwire.com>"]

[dependencies]
generic_game = { path="C:/Users/Jonesey13/projects/generic_game" }
nalgebra = "*"
num = "*"
time = "*"
lazy_static = "*"
rand = "*"
image = "*"
glium = "*"
rusttype = "*"